/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsWhatsappAutomationRouteImport } from './routes/solutions.whatsapp-automation'
import { Route as SolutionsUiUxDesignRouteImport } from './routes/solutions.ui-ux-design'
import { Route as SolutionsMobileAppDevelopmentRouteImport } from './routes/solutions.mobile-app-development'
import { Route as SolutionsCloudSolutionsRouteImport } from './routes/solutions.cloud-solutions'
import { Route as SolutionsBusinessAutomationRouteImport } from './routes/solutions.business-automation'
import { Route as SolutionsApiIntegrationsRouteImport } from './routes/solutions.api-integrations'
import { Route as SolutionsAnalyticsDashboardsRouteImport } from './routes/solutions.analytics-dashboards'
import { Route as SolutionsAiAgentsRouteImport } from './routes/solutions.ai-agents'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWhatsappAutomationRoute =
  SolutionsWhatsappAutomationRouteImport.update({
    id: '/whatsapp-automation',
    path: '/whatsapp-automation',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsUiUxDesignRoute = SolutionsUiUxDesignRouteImport.update({
  id: '/ui-ux-design',
  path: '/ui-ux-design',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsMobileAppDevelopmentRoute =
  SolutionsMobileAppDevelopmentRouteImport.update({
    id: '/mobile-app-development',
    path: '/mobile-app-development',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsCloudSolutionsRoute = SolutionsCloudSolutionsRouteImport.update({
  id: '/cloud-solutions',
  path: '/cloud-solutions',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsBusinessAutomationRoute =
  SolutionsBusinessAutomationRouteImport.update({
    id: '/business-automation',
    path: '/business-automation',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsApiIntegrationsRoute =
  SolutionsApiIntegrationsRouteImport.update({
    id: '/api-integrations',
    path: '/api-integrations',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsAnalyticsDashboardsRoute =
  SolutionsAnalyticsDashboardsRouteImport.update({
    id: '/analytics-dashboards',
    path: '/analytics-dashboards',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsAiAgentsRoute = SolutionsAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => SolutionsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/mcp': typeof McpRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/analytics-dashboards': typeof SolutionsAnalyticsDashboardsRoute
  '/solutions/api-integrations': typeof SolutionsApiIntegrationsRoute
  '/solutions/business-automation': typeof SolutionsBusinessAutomationRoute
  '/solutions/cloud-solutions': typeof SolutionsCloudSolutionsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/whatsapp-automation': typeof SolutionsWhatsappAutomationRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/mcp': typeof McpRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/analytics-dashboards': typeof SolutionsAnalyticsDashboardsRoute
  '/solutions/api-integrations': typeof SolutionsApiIntegrationsRoute
  '/solutions/business-automation': typeof SolutionsBusinessAutomationRoute
  '/solutions/cloud-solutions': typeof SolutionsCloudSolutionsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/whatsapp-automation': typeof SolutionsWhatsappAutomationRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/mcp': typeof McpRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/solutions/ai-agents': typeof SolutionsAiAgentsRoute
  '/solutions/analytics-dashboards': typeof SolutionsAnalyticsDashboardsRoute
  '/solutions/api-integrations': typeof SolutionsApiIntegrationsRoute
  '/solutions/business-automation': typeof SolutionsBusinessAutomationRoute
  '/solutions/cloud-solutions': typeof SolutionsCloudSolutionsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/whatsapp-automation': typeof SolutionsWhatsappAutomationRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/how-we-work'
    | '/mcp'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/solutions/ai-agents'
    | '/solutions/analytics-dashboards'
    | '/solutions/api-integrations'
    | '/solutions/business-automation'
    | '/solutions/cloud-solutions'
    | '/solutions/mobile-app-development'
    | '/solutions/ui-ux-design'
    | '/solutions/whatsapp-automation'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/how-we-work'
    | '/mcp'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/solutions/ai-agents'
    | '/solutions/analytics-dashboards'
    | '/solutions/api-integrations'
    | '/solutions/business-automation'
    | '/solutions/cloud-solutions'
    | '/solutions/mobile-app-development'
    | '/solutions/ui-ux-design'
    | '/solutions/whatsapp-automation'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/how-we-work'
    | '/mcp'
    | '/solutions'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/solutions/ai-agents'
    | '/solutions/analytics-dashboards'
    | '/solutions/api-integrations'
    | '/solutions/business-automation'
    | '/solutions/cloud-solutions'
    | '/solutions/mobile-app-development'
    | '/solutions/ui-ux-design'
    | '/solutions/whatsapp-automation'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  McpRoute: typeof McpRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/whatsapp-automation': {
      id: '/solutions/whatsapp-automation'
      path: '/whatsapp-automation'
      fullPath: '/solutions/whatsapp-automation'
      preLoaderRoute: typeof SolutionsWhatsappAutomationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ui-ux-design': {
      id: '/solutions/ui-ux-design'
      path: '/ui-ux-design'
      fullPath: '/solutions/ui-ux-design'
      preLoaderRoute: typeof SolutionsUiUxDesignRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/mobile-app-development': {
      id: '/solutions/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/solutions/mobile-app-development'
      preLoaderRoute: typeof SolutionsMobileAppDevelopmentRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/cloud-solutions': {
      id: '/solutions/cloud-solutions'
      path: '/cloud-solutions'
      fullPath: '/solutions/cloud-solutions'
      preLoaderRoute: typeof SolutionsCloudSolutionsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/business-automation': {
      id: '/solutions/business-automation'
      path: '/business-automation'
      fullPath: '/solutions/business-automation'
      preLoaderRoute: typeof SolutionsBusinessAutomationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/api-integrations': {
      id: '/solutions/api-integrations'
      path: '/api-integrations'
      fullPath: '/solutions/api-integrations'
      preLoaderRoute: typeof SolutionsApiIntegrationsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/analytics-dashboards': {
      id: '/solutions/analytics-dashboards'
      path: '/analytics-dashboards'
      fullPath: '/solutions/analytics-dashboards'
      preLoaderRoute: typeof SolutionsAnalyticsDashboardsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/ai-agents': {
      id: '/solutions/ai-agents'
      path: '/ai-agents'
      fullPath: '/solutions/ai-agents'
      preLoaderRoute: typeof SolutionsAiAgentsRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsAiAgentsRoute: typeof SolutionsAiAgentsRoute
  SolutionsAnalyticsDashboardsRoute: typeof SolutionsAnalyticsDashboardsRoute
  SolutionsApiIntegrationsRoute: typeof SolutionsApiIntegrationsRoute
  SolutionsBusinessAutomationRoute: typeof SolutionsBusinessAutomationRoute
  SolutionsCloudSolutionsRoute: typeof SolutionsCloudSolutionsRoute
  SolutionsMobileAppDevelopmentRoute: typeof SolutionsMobileAppDevelopmentRoute
  SolutionsUiUxDesignRoute: typeof SolutionsUiUxDesignRoute
  SolutionsWhatsappAutomationRoute: typeof SolutionsWhatsappAutomationRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAiAgentsRoute: SolutionsAiAgentsRoute,
  SolutionsAnalyticsDashboardsRoute: SolutionsAnalyticsDashboardsRoute,
  SolutionsApiIntegrationsRoute: SolutionsApiIntegrationsRoute,
  SolutionsBusinessAutomationRoute: SolutionsBusinessAutomationRoute,
  SolutionsCloudSolutionsRoute: SolutionsCloudSolutionsRoute,
  SolutionsMobileAppDevelopmentRoute: SolutionsMobileAppDevelopmentRoute,
  SolutionsUiUxDesignRoute: SolutionsUiUxDesignRoute,
  SolutionsWhatsappAutomationRoute: SolutionsWhatsappAutomationRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  McpRoute: McpRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
